# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://dlegor.github.io/dive_into_fastai/"

git_url = "https://github.com/dlegor/dive_into_fastai/tree/master/"

def custom_doc_links(name): return None
